[package]
name = "contract"
version = "0.1.0"
edition = "2024"
rust-version = "1.92"
build = "build.rs"

[lib]
name = "contract"
path = "src/lib.rs"

[[bin]]
name = "contract"
path = "src/contract.rs"

[dependencies]
alloy-core = { version = "1.6", default-features = false, features = ["sol-types"] }
pallet-revive-uapi = { version = "0.14", default-features = false }
picoalloc = { version = "5", default-features = false }
polkavm-derive = { version = "0.33.0" }
parity-scale-codec = { version = "*", default-features = false }

[build-dependencies]
cargo-pvm-contract-builder = "0.3.0"

[features]
std = []


[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
overflow-checks = false
