[package]
name = "contract"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[lib]
name = "contract"
path = "src/lib.rs"

[[bin]]
name = "contract"
path = "src/contract.rs"

[dependencies]
alloy-core = { version = "*", default-features = false, features = ["sol-types"] }
pallet-revive-uapi = { version = "*", default-features = false }
picoalloc = { version = "*", default-features = false }
polkavm-derive = { version = "*" }
parity-scale-codec = { version = "*", default-features = false }

[build-dependencies]
cargo-pvm-contract-builder = "*"

[features]
std = []


[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
overflow-checks = false
